name: Release 

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ trunk ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Luacheck
        run: |
          sudo apt-get install luarocks
          luarocks install --local luacheck
          /home/runner/.luarocks/bin/luacheck . --no-color -q

      - uses: BigWigsMods/packager@v2
        with:
          args: -n "{package-name}"
      #env:
        #  CF_API_KEY: ${{ secrets.CF_API_KEY }}
        #  WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
        #  GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: actions/upload-artifact@v4
        with:
          name: TangraUnitFrames.zip
          path: TangraUnitFrames_.zip 
          retention-days: 1
          overwrite: true